### PR TITLE
add papers we love

### PR DESCRIPTION
**Pull request by aische**
we created a folder called papers and added some papers. it' work in progress and will be extended, so maybe wait with merging it.

cc @daniel-j-h

### CODE REVIEW

**Comment by sjsyrek** [comment]
So I shouldn't merge it yet?

**Comment by aische** [comment]
I guess you can merge it. Our plan is to collect "classical" Haskell papers, then make a selection and discuss which of them we actually want to read. This will probably take a while, so the list will change. 

cc @daniel-j-h is that ok for you?

**Comment by daniel-j-h** [comment]
Yep okay, feel free to merge already we can change it later on.

**Comment by sjsyrek** [comment]
The only change I'm going to make on my end is to make README uppercase in the filename, but only so I can sleep at night.

**Pull request merged**
